baseURL = 'http://example.org/'
languageCode = 'en-us'
title = "Coco's resume"
theme = 'hugo-devresume-theme'
googleAnalytics = "UA-XXXXXXX-Y"


[params]
    author = "李晶"
    description = "Coco's resume"

    primaryColor = "#54B689"
    textPrimaryColor = "#292929"

    [params.profile]
        enable = true
        name = "李晶"
        tagline = "Intermediate Front-end Development Engineer"
        avatar = "/lijing.jpg"

    [params.contact]
        enable = true
        location = "深圳"

        [[params.contact.list]]
        icon = "fas fa-phone-square"
        url = "tel:+8613168010071"
        text = "+8613168010071"
        [[params.contact.list]]
        icon = "fas fa-envelope-square"
        url = "mailto:956115252@qq.com"
        text = "956115252@qq.com"
        [[params.contact.list]]
        icon = "fas fa-globe"
        url = "http://www.dreamrounder.com"
        text = "www.dreamrounder.com"

    [params.summary]
        enable = true
        text = "目前就职于嘉联支付，主要使用vue, jquery与react开发h5, 小程序等前端应用，曾经也参与过.net的服务端开发，具备一定后端知识。"

    [params.experience]
        enable = true

        [[params.experience.list]]
        title = "Front-end Development Engineer"
        dates = "2020 - 至今"
        company = "嘉联支付"
        details = "负责公司内部系统与ToC移动端（小程序、公众号、Hybrid App等）的研发与维护"
        [[params.experience.list.items]]
        details = "快速学习微信小程序和uni-app，并按期交付小餐宝点餐系统 "
        [[params.experience.list.items]]
        details = "主导遗留项目的重构，完成从JQuery到Vue转型；同时沉淀可复用代码，提升维护效率"

        [[params.experience.list]]
        title = "Front-end Development Engineer"
        dates = "2019 - 2020"
        company = "万汇互联"
        details = "Lagoon CRM系统前端负责人，同时参与OA系统、部分官网子项目的开发"
        [[params.experience.list.items]]
        details = "快速上手Vue全家桶，并投入线上项目的研发"
        [[params.experience.list.items]]
        details = "主导完成Lagoon CRM V3.0，抽出大量表单组件，使项目代码更加精简、清晰，更易于维护 "

        [[params.experience.list]]
        title = "Client Development Engineer"
        dates = "2017 - 2019"
        company = "深圳巨鼎医疗设备有限公司"
        details = "负责银医通客户端与服务端的开发、相关硬件的测试及医院定制化需求开发"
        [[params.experience.list.items]]
        details = "参与银医通客户端的UI重构，将原有WPF改为H5+Webkit的形式"
        [[params.experience.list.items]]
        details = "解耦客户端与硬件通信过程，由dll切换为API调用"

    [params.skills]
        enable = true

        [[params.skills.list]]
        title = "技术栈"
        [[params.skills.list.items]]
        details = "HTML/CSS/Javascript"
        [[params.skills.list.items]]
        details = "Vue/JQuery/小程序"
        [[params.skills.list.items]]
        details = "Sass/Less/Stylus"
        [[params.skills.list.items]]
        details = "Webpack/Npm/Yarn"
        [[params.skills.list.items]]
        details = "DotNet/Webservice/Mysql"

    [params.education]
        enable = true

        [[params.education.list]]
        degree = "软件工程"
        university = "华中科技大学武昌分校"
        dates = "2013 - 2017"

    [params.awards]
        enable = true

        [[params.awards.list]]
        name = "信息系统项目管理师"
        body = "软考高级职称——信息系统项目管理师"
        date = "2021"
        [[params.awards.list]]
        name = "PMP"
        body = "项目管理专业人士资格认证"
        date = "2020"

    [params.languages]
        enable = true

        [[params.languages.list]]
        name = "中文"
        level = "Native"
        [[params.languages.list]]
        name = "英文"
        level = "CET6"

    [params.projects]
        enable = true

        [[params.projects.list]]
        title = "小餐宝"
        meta = "嘉联支付"
        tagline = "小餐宝作为公司的增值业务，针对小型餐饮商户设计，满足客户到店点单、下单自取、外卖的需求。也向商户提供商品的管理、子账号和订单的管理，营收状况的查询等功能。"
        [[params.projects.list.desc]]
        text = "快速学习并上手微信小程序和uni-app"
        [[params.projects.list.desc]]
        text = "搭建客户端uni-app项目，引入uview-UI框架，封装公共方法和组件"
        [[params.projects.list.desc]]
        text = "利用Websocket实现多人同时点餐功能"
        [[params.projects.list.desc]]
        text = "使用canvas绘制商家端桌码"

        [[params.projects.list]]
        title = "大丰对账平台重构"
        meta = "嘉联支付"
        tagline = "该项目针对澳门地区的商户，将公司原有的商户对账平台的部分功能进行删改，使得商户可以查看自己的交易信息、对账单、收入流水以及下载账单等。且在原有功能基础上新增加集团类型的用户，可以查看集团下面各个商户的信息，及集团总体经营状况。"
        [[params.projects.list.desc]]
        text = " 将Jsp + JQuey的模式重构成Vue项目，且前后端分离"
        [[params.projects.list.desc]]
        text = "二次封装Element UI，形成适合本项目的表格组件、时间组件、多选项搜索组件"
        [[params.projects.list.desc]]
        text = "采用Echarts绘制月收入流水的图表"
        [[params.projects.list.desc]]
        text = "采用将用户信息存储位置分开的方式，使得用户可以同时登录集团账号和商户账号进行操作，并且互不影响"

        [[params.projects.list]]
        title = "Lagoon CRM V3.0"
        meta = "万汇互联"
        tagline = "本项目是主要针对公司客服和销售做跟进及销售任务用，是一个重构版本。功能上对前Lagoon和CRM项目进行整合，并调整了UI风格及交互方式"
        [[params.projects.list.desc]]
        text = "根据UI需求，将UI框架由Element改成IView，并在IView 组件基础上进行样式和交互方式改造"
        [[params.projects.list.desc]]
        text = "完成所有共通组件的封装，且增加自定义指令以及mixin混入提高开发效率"
        [[params.projects.list.desc]]
        text = "接入IM即时通讯，完成客服聊天系统"
        [[params.projects.list.desc]]
        text = "利用webpack对包体积进行优化"

        [[params.projects.list]]
        title = "银医通 V3.1"
        meta = "深圳市巨鼎医疗设备有限公司"
        tagline = "银医通是一个终端桌面软件，主要用于医院就诊患者的建档、挂号、缴费等"
        [[params.projects.list.desc]]
        text = "客户端由WPF切换为WebKit+jQuery+html静态页面的构建模式"
        [[params.projects.list.desc]]
        text = "将Webservice服务更新为WebAPI服务，接口采用RestfulAPI规范"
        [[params.projects.list.desc]]
        text = "解耦硬件服务，将dll调用改为http调用"

    [params.social]
        enable = false

        [[params.social.list]]
        icon = "fab fa-github-square"
        url = "https://github.com/CocoLee9561"
        title = "CocoLee"
        [[params.social.list]]
        icon = "fab fa-linkedin"
        url = "https://www.linkedin.com/in/%E9%91%AB-%E5%BE%90-929452140/"
        title = "XuXin"
